services:
  - type: web
    name: observatorio-pi
    runtime: python
    region: oregon
    plan: free
    rootDir: observatorio_pi
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sh start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@observatorio.pi
      - key: ADMIN_PASSWORD
        value: admin1234
      - key: PYTHON_VERSION
        value: "3.11.0"
